"""added soft_delete row

Revision ID: 0e0dfd173d34
Revises: 25ea58837c90
Create Date: 2025-09-23 14:41:40.182353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0dfd173d34'
down_revision: Union[str, None] = '25ea58837c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'is_deleted')
    # ### end Alembic commands ###
