"""update table

Revision ID: 63fa179aabd8
Revises: b51991d9bd0b
Create Date: 2025-10-14 15:20:22.974527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fa179aabd8'
down_revision: Union[str, None] = 'b51991d9bd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_updates', sa.Column('tracking_id', sa.String(), nullable=False))
    op.add_column('delivery_updates', sa.Column('status', sa.String(), nullable=False))
    op.add_column('delivery_updates', sa.Column('location', sa.String(), nullable=True))
    op.add_column('delivery_updates', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('delivery_updates', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.create_foreign_key(None, 'delivery_updates', 'tracking', ['tracking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_updates', type_='foreignkey')
    op.drop_column('delivery_updates', 'is_deleted')
    op.drop_column('delivery_updates', 'remarks')
    op.drop_column('delivery_updates', 'location')
    op.drop_column('delivery_updates', 'status')
    op.drop_column('delivery_updates', 'tracking_id')
    # ### end Alembic commands ###
