"""tracking tables

Revision ID: d26d226ebf75
Revises: 5d44ff5f4667
Create Date: 2025-08-15 15:09:57.461041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26d226ebf75'
down_revision: Union[str, None] = '5d44ff5f4667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('name_of_package', sa.String(), nullable=False),
    sa.Column('delivery_destination', sa.String(), nullable=False),
    sa.Column('dispatch_location', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_picture', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_index(op.f('ix_tracking_id'), 'tracking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_id'), table_name='tracking')
    op.drop_table('tracking')
    # ### end Alembic commands ###
